; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
# ★ 重点：锁死平台版本为 6.9.0，这对应的是旧版 API 架构，保证你的代码永远有效
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino

# 串口监视器波特率
monitor_speed = 115200
# 烧录速度
upload_speed = 921600

# === ★ N16R8 (16MB Flash + 8MB PSRAM) 核心配置 ★ ===
# 必须使用 qio_opi 模式，ESP32-S3 才能识别 8MB 的八线 PSRAM
board_build.arduino.memory_type = qio_opi
# 开启 PSRAM 硬件支持
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

# 指定 Flash 大小为 16MB (默认只有 8MB)
board_upload.flash_size = 16MB
# 自动分配 Flash 分区表给 16MB 使用
board_build.partitions = default_16MB.csv

# 依赖库
lib_deps = 
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2